- name: 'backlog'
  color: '4b1f8e'
- name: 'wontfix'
  color: '4b1f8e'
- name: 'discussion'
  color: '4b1f8e'
- name: 'duplicate'
  color: '4b1f8e'
- name: 'approved'
  color: '4b1f8e'
- name: 'review in progress'
  color: '4b1f8e'
- name: 'invalid'
  color: '4b1f8e'

- name: 'feature'
  color: '0075ca'
- name: 'bug'
  color: '0075ca'
- name: 'chore'
  color: '0075ca'
- name: 'ci'
  color: '0075ca'
- name: 'dependencies'
  color: '0075ca'
- name: 'refactor'
  color: '0075ca'
- name: 'regression'
  color: '0075ca'

- name: 'priority:high'
  color: 'fc1423'
- name: 'priority:medium'
  color: 'fc1423'
- name: 'priority:low'
  color: 'fc1423'

- name: 'semver:major'
  color: '0fc174'
- name: 'semver:minor'
  color: '0fc174'
- name: 'semver:patch'
  color: '0fc174'

- name: 'typings'
  color: '80c042'
- name: 'utility'
  color: '80c042'
- name: 'functions'
  color: '80c042'
- name: 'commands'
  color: '80c042'
- name: 'events'
  color: '80c042'
- name: 'managers'
  color: '80c042'
- name: 'structures'
  color: '80c042'
- name: 'database'
  color: '80c042'