[discord]
PUBLIC_KEY = "d781f44f171c6ad0a1d89ebbf72a346ec3ff8b057d3e875d4042dcac4488f08a"
TOKEN = "OTM0MTIxODg3ODI5NzM3NTYy.GL_tTT.Vu8jrxGw2GmDf5qVhzklO37eadDsEV_OevGHqo"

[fastify]
PORT = 8080

[interval]
DEV_API_KEY = "joshua_dev_4B6rTXm60WZXJtB40DVO3AeNFPeNzTvMdw2G0Kkxbx3JaIZE"
PRODUCTION_API_KEY = "live_uCJNxdxnkExWapjGQgNNhdxrPJdE3Rtm2vL9WQdI69IeY5hz"

[sentry]
