[discord]
PUBLIC_KEY = "d781f44f171c6ad0a1d89ebbf72a346ec3ff8b057d3e875d4042dcac4488f08a"
TOKEN = "OTM0MTIxODg3ODI5NzM3NTYy.GlYKP0.mZZvOAXqCLTCi0ySX2h2wcAyvhuGBIAcypDVSo"

[fastify]
PORT = 8080

[interval]
DEV_API_KEY = "joshua_dev_4B6rTXm60WZXJtB40DVO3AeNFPeNzTvMdw2G0Kkxbx3JaIZE"
PRODUCTION_API_KEY = "live_uCJNxdxnkExWapjGQgNNhdxrPJdE3Rtm2vL9WQdI69IeY5hz"

[proxy]
PORT = 3000

[clamav]
MIRROR = "https://mirror.penpow.dev"

[sentry]
DATABASE_URL = "postgresql://sentry:postgres@postgres:5432/mydb?schema=public"
ENCRYPTION_KEY = "k1.aesgcm256.TMO1mNKCTt5nl5RDfTVyaEQCt_CxncqRyeJHYsUuzVI="