version: "3.9"
services:
  sentry:
    container_name: bot
    build:
      context: .
      dockerfile: ./docker/Bot.Dockerfile
    tty: true
    restart: always
    ports:
      - 8080:8080
    links:
      - redis:redis
      - rest:rest
    depends_on:
      redis:
        condition: service_healthy
      rest:
        condition: service_started

  ws-proxy:
    container_name: ws-proxy
    build:
      context: .
      dockerfile: ./docker/Websocket.Dockerfile
    tty: true
    restart: always
    links:
      - redis:redis
    depends_on:
      redis:
        condition: service_healthy
      rest:
        condition: service_started

  rest:
    container_name: rest-proxy
    expose:
      - "3000:3000"
    restart: always
    build:
      context: .
      dockerfile: ./docker/Rest.Dockerfile
    tty: true

  redis:
    image: redis:7.0.5-alpine
    restart: always
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s