version: "3.9"
services:
  sentry:
    container_name: sentry
    image: ghcr.io/penpow/sentry:latest
    pull_policy: always
    tty: true
    environment:
      - SENTRY_VERSION
    env_file:
      - .env
    restart: always
    links:
      - postgres:postgres
      - redis:redis
      - clamav:clamav
    depends_on:
      postgres:
          condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sentry']
      interval: 10s
      timeout: 5s

  redis:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s

  clamd:
    image: clamav/clamav:0.104
    restart: unless-stopped
  
  clamav:
    image: benzino77/clamav-rest-api
    restart: always
    links:
      - clamd:clamd
    depends_on:
      - clamd
    environment:
      - NODE_ENV=production
      - CLAMD_IP=clamd
      - APP_FORM_KEY=FILES
      - APP_PORT=3000
    ports:
      - '8080:3000'

volumes:
  postgres:
    driver: local
