version: "3.9"
services:
  sentry:
    container_name: sentry
    image: ghcr.io/penpow/sentry:latest
    tty: true
    env_file:
      - .env
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    depends_on:
      postgres:
          condition: service_healthy
      redis:
        condition: service_healthy
  
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sentry']
      interval: 10s
      timeout: 5s

  redis:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s

volumes:
  postgres:
    driver: local