name: Build and Linting CI

on:
  push:
    branches: [main]
    paths:
      - "apps/**"
      - "packages/**"
      - "package*.json"
  pull_request:
    branches: [main]
    paths:
      - "apps/**"
      - "packages/**"
      - "package*.json"
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'penpow/sentry'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm set-script prepare ""
        
      - name: Install Dependencies
        run: npm ci

      - name: Build Packages
        run: npm run build
      
  lint:
    runs-on: ubuntu-latest
    if: github.repository == 'penpow/sentry'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm set-script prepare ""

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint