name: Linting CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package*.json"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package*.json"
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'penpow/sentry'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm set-script prepare ""
        
      - name: Install Dependencies
        run: npm ci

      - name: Build Typescript
        run: npm run build
      
  lint:
    runs-on: ubuntu-latest
    if: github.repository == 'penpow/sentry'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm set-script prepare ""

      - run: npm ci
        
      - name: Run ESLint
        run: npm run lint