name: Deno CI

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - .github/**
      - importMap.json
      - LICENSE.md
      - .gitignore
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint Deno
        run: deno lint